// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smqgdywkyvgllosfmxmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtcWdkeXdreXZnbGxvc2ZteG1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NzMxMTksImV4cCI6MjA1OTI0OTExOX0.4iUBushWYGQLw84tHNN8uPslry37QXxcIrevlfwXnN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);